// <auto-generated />
using Life_Insurance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Life_Insurance.Migrations
{
    [DbContext(typeof(Mycontext))]
    [Migration("20241205021830_update-claimsssssss")]
    partial class updateclaimsssssss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Life_Insurance.Models.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<string>("admin_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_id");

                    b.ToTable("tbl_admin");
                });

            modelBuilder.Entity("Life_Insurance.Models.Claim", b =>
                {
                    b.Property<int>("claim_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("claim_id"));

                    b.Property<string>("claim_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claim_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claim_useremail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claim_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claim_userphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claim_userpolicynumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("claim_id");

                    b.ToTable("tbl_claim");
                });

            modelBuilder.Entity("Life_Insurance.Models.Contact", b =>
                {
                    b.Property<int>("contact_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contact_id"));

                    b.Property<string>("contact_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("contact_id");

                    b.ToTable("tbl_contact");
                });

            modelBuilder.Entity("Life_Insurance.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("insurancepolicy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("insurancepolicy_id"));

                    b.Property<string>("insurancepolicy_covergeamount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insurancepolicy_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insurancepolicy_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insurancepolicy_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insurancepolicy_premiumamount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("policytype_id")
                        .HasColumnType("int");

                    b.Property<int>("termplanyearly_id")
                        .HasColumnType("int");

                    b.HasKey("insurancepolicy_id");

                    b.HasIndex("policytype_id");

                    b.HasIndex("termplanyearly_id");

                    b.ToTable("tbl_insurancepolicy");
                });

            modelBuilder.Entity("Life_Insurance.Models.Loan", b =>
                {
                    b.Property<int>("loan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loan_id"));

                    b.Property<string>("loan_amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loan_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loan_repaymentamount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("termplanyearlymonthly_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("loan_id");

                    b.HasIndex("termplanyearlymonthly_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_loan");
                });

            modelBuilder.Entity("Life_Insurance.Models.News", b =>
                {
                    b.Property<int>("news_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("news_id"));

                    b.Property<string>("news_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("news_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("news_id");

                    b.ToTable("tbl_news");
                });

            modelBuilder.Entity("Life_Insurance.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("paymenttransaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymenttransaction_id"));

                    b.Property<int>("insurancepolicy_id")
                        .HasColumnType("int");

                    b.Property<string>("paymenttransaction_amountpaid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymenttransaction_paymentdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("termplanyearlymonthly_id")
                        .HasColumnType("int");

                    b.Property<int>("transactiontype_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("paymenttransaction_id");

                    b.HasIndex("insurancepolicy_id");

                    b.HasIndex("termplanyearlymonthly_id");

                    b.HasIndex("transactiontype_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_paymenttransaction");
                });

            modelBuilder.Entity("Life_Insurance.Models.PolicyType", b =>
                {
                    b.Property<int>("policytype_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("policytype_id"));

                    b.Property<string>("policytype_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("policytype_id");

                    b.ToTable("tbl_policytype");
                });

            modelBuilder.Entity("Life_Insurance.Models.PremiumCalculation", b =>
                {
                    b.Property<int>("premiumcalculation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("premiumcalculation_id"));

                    b.Property<int>("insurancepolicy_id")
                        .HasColumnType("int");

                    b.Property<string>("premiumcalculation_calculatedpremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("premiumcalculation_calculationdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("termplanyearlymonthly_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("premiumcalculation_id");

                    b.HasIndex("insurancepolicy_id");

                    b.HasIndex("termplanyearlymonthly_id");

                    b.HasIndex("user_id");

                    b.ToTable("tbl_premiumcalculation");
                });

            modelBuilder.Entity("Life_Insurance.Models.TermPlanYearly", b =>
                {
                    b.Property<int>("termplanyearly_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("termplanyearly_id"));

                    b.Property<string>("termplanyearly_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("termplanyearly_id");

                    b.ToTable("tbl_termplanyearly");
                });

            modelBuilder.Entity("Life_Insurance.Models.TermPlanYearlyMonthly", b =>
                {
                    b.Property<int>("termplanyearlymonthly_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("termplanyearlymonthly_id"));

                    b.Property<string>("termplanyearlymonthly_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("termplanyearlymonthly_id");

                    b.ToTable("tbl_termplanyearlymonthly");
                });

            modelBuilder.Entity("Life_Insurance.Models.TransactionType", b =>
                {
                    b.Property<int>("transactiontype_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transactiontype_id"));

                    b.Property<string>("transactiontype_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("transactiontype_id");

                    b.ToTable("tbl_transactiontype");
                });

            modelBuilder.Entity("Life_Insurance.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("user_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_cnic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_dateofbirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("tbl_users");
                });

            modelBuilder.Entity("Life_Insurance.Models.UserPolicy", b =>
                {
                    b.Property<int>("userpolicy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userpolicy_id"));

                    b.Property<int>("insurancepolicy_id")
                        .HasColumnType("int");

                    b.Property<int>("termplanyearly_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("userpolicy_enddate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userpolicy_premiumpaid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userpolicy_startdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userpolicy_id");

                    b.ToTable("tbl_userpolicy");
                });

            modelBuilder.Entity("Life_Insurance.Models.faqs", b =>
                {
                    b.Property<int>("faqs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("faqs_id"));

                    b.Property<string>("faqs_answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faqs_question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("faqs_id");

                    b.ToTable("tbl_faqs");
                });

            modelBuilder.Entity("Life_Insurance.Models.feedback", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("feedback_id"));

                    b.Property<string>("feedback_message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("feedback_id");

                    b.ToTable("tbl_feedback");
                });

            modelBuilder.Entity("Life_Insurance.Models.InsurancePolicy", b =>
                {
                    b.HasOne("Life_Insurance.Models.PolicyType", "PolicyType")
                        .WithMany()
                        .HasForeignKey("policytype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_Insurance.Models.TermPlanYearly", "TermPlanYearly")
                        .WithMany()
                        .HasForeignKey("termplanyearly_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyType");

                    b.Navigation("TermPlanYearly");
                });

            modelBuilder.Entity("Life_Insurance.Models.Loan", b =>
                {
                    b.HasOne("Life_Insurance.Models.TermPlanYearlyMonthly", "TermPlanYearlyMonthly")
                        .WithMany()
                        .HasForeignKey("termplanyearlymonthly_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_Insurance.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermPlanYearlyMonthly");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Life_Insurance.Models.PaymentTransaction", b =>
                {
                    b.HasOne("Life_Insurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithMany()
                        .HasForeignKey("insurancepolicy_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_Insurance.Models.TermPlanYearlyMonthly", "TermPlanYearlyMonthly")
                        .WithMany()
                        .HasForeignKey("termplanyearlymonthly_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_Insurance.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("transactiontype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_Insurance.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");

                    b.Navigation("TermPlanYearlyMonthly");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Life_Insurance.Models.PremiumCalculation", b =>
                {
                    b.HasOne("Life_Insurance.Models.InsurancePolicy", "InsurancePolicy")
                        .WithMany()
                        .HasForeignKey("insurancepolicy_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_Insurance.Models.TermPlanYearlyMonthly", "TermPlanYearlyMonthly")
                        .WithMany()
                        .HasForeignKey("termplanyearlymonthly_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Life_Insurance.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");

                    b.Navigation("TermPlanYearlyMonthly");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
